# Generated by Django 3.2.7 on 2021-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_auto_20211010_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='agree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='disagree',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue',
            name='moderator',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue_reply',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='issue_rereply',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
