# Generated by Django 3.2.7 on 2021-10-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_auto_20211010_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='agree_represent',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='agree_representor',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='disagree_represent',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='disagree_representor',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
