# Generated by Django 3.2.7 on 2021-10-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_auto_20211010_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='agree_representor_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='disagree_representor_id',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='agree_representor',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='disagree_representor',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
