# Generated by Django 3.2.7 on 2021-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_auto_20211010_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='youtube',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
