# Generated by Django 3.2.7 on 2021-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_issue_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_reply',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='issue_rereply',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
