# Generated by Django 3.2.7 on 2021-10-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_auto_20211010_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('image', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pybo.topic'),
        ),
    ]
